repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: debug-statements

  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
        language_version: python3
        files: '\.py$'

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black"]
        files: '\.py$'

  # - repo: https://github.com/pycqa/flake8
  #   rev: 6.1.0
  #   hooks:
  #     - id: flake8
  #       additional_dependencies: [flake8-docstrings, flake8-import-order]
  #       files: '\.py$'

  # MyPy disabled in pre-commit due to environment issues
  # Run manually with: make type-check
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.5.1
  #   hooks:
  #     - id: mypy
  #       additional_dependencies: [types-requests, types-pyaudio, types-selenium]
  #       args: [--ignore-missing-imports, --no-strict-optional]
  #       files: '\.py$'
